# Generated by Django 4.0.2 on 2022-05-02 14:13

import concurrency.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название департамента')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'рядовой сотрудник'), ('MANAGER', 'менеджер')], default='EMPLOYEE', max_length=25)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DRAFT', 'Черновое'), ('PUBLISHED', 'Опубликовано'), ('HIDDEN', 'Скрыто')], default='DRAFT', max_length=25, verbose_name='Состояние')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/Время публикации')),
                ('_version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.user')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
