# Generated by Django 4.0.2 on 2022-05-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('APPLICANT', 'соискатель'), ('MANAGER', 'менеджер')], default='APPLICANT', max_length=25),
        ),
    ]
