# Generated by Django 4.0.2 on 2022-04-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'рядовой сотрудник'), ('MANAGER', 'менеджер')], default='EMPLOYEE', max_length=25),
        ),
    ]
