# Generated by Django 4.0.2 on 2022-05-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='_version',
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DRAFT', 'Черновая'), ('PUBLISHED', 'Опубликована'), ('HIDDEN', 'Скрыта')], default='DRAFT', max_length=50, verbose_name='Состояние')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('experience', models.PositiveIntegerField(blank=True, help_text='В годах', null=True, verbose_name='Стаж работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата/Время создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/Время публикации')),
                ('creator', models.ForeignKey(help_text='Менеджер, разместивший вакансию', on_delete=django.db.models.deletion.CASCADE, to='hr.user')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
