# Generated by Django 4.0.2 on 2022-06-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_skill_remove_resume_content_resume_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_message', models.TextField(blank=True, null=True, verbose_name='Сопроводительное письмо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hr.resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hr.vacancy')),
            ],
            options={
                'verbose_name': 'отклик на вакансию',
                'verbose_name_plural': 'отклики на вакансию',
            },
        ),
    ]
